server:
  port: 8080
spring:
  cache:
    cache-names:
      - fuck-yeah-cache
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  redis:
    database: 0
    host: "localhost"
    port: 6379

rest:
  foaas-base-url: "https://www.foaas.com"

rate-limit:
  refill:
    period: 10
    unit: "seconds"
  bucket-size: 5